#pragma once

#define DESCRIBE_JSON_SIZE 4096
#define ACTION_STATUS_JSON_SIZE 1024
#define PROPERTY_STATUS_JSON_SIZE 512
#define SMALL_MESSAGE_JSON_SIZE 256
#define INCOMING_JSON_CAPACITY 2048

#ifndef LIGHTHOUSE_CLIENT_MAX
#define LIGHTHOUSE_CLIENT_MAX 5
#endif

#define WIFI_CONNECTING_MAX_TIME 20000 // 20000ms = 20s